apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordlist-deployment
spec:
  replicas: 3  # Set the desired number of replicas to 3
  selector:
    matchLabels:
      app: wordlist
  template:
    metadata:
      labels:
        app: wordlist
    spec:
      containers:
        - name: wordlist-container
          image: com.cgm.life/wordlist:1.0.0
          ports:
            - containerPort: 80
