apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordlist-deployment
spec:
  replicas: 3  # Set the number of desired replicas
  selector:
    matchLabels:
      app: wordlist
  template:
    metadata:
      labels:
        app: wordlist
    spec:
      containers:
        - name: wordlist-container
          image: word-list:3.7.12
          ports:
            - containerPort: 8080

